# Generated by Django 4.2.13 on 2025-03-16 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone number'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpirableToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('expires_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Expires at')),
            ],
            options={
                'verbose_name': 'ExpirableToken',
                'verbose_name_plural': 'ExpirableTokens',
                'abstract': False,
                'ordering': ['-expires_at'],
            },
        ),
    ]
